### ISSUE TITLE
Check that `current` exists on ref before trying to use it

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-click-outside#2]
Within the source code you use `ref.current.contains`, but for whatever reason the refs I pass into it in [`@ninetynine/react-dropdown`](https://github.com/ninetynine/react-dropdown) do not have `current`, but `contains` is directly on the ref. So I check on the event [callback](https://github.com/ninetynine/react-dropdown/blob/master/src/dropdown.jsx#L65-L73).

```jsx
    handleClick(event) {
        let {onClickOutside, ignoreRefs} = this.props;

        let clickedOutside = true;

        if (ignoreRefs) {
            if (!Array.isArray(ignoreRefs)) {
                ignoreRefs = [ignoreRefs];
            }

            ignoreRefs.forEach((ref) => {
                if (ref.current.contains(event.target)) {
                    clickedOutside = false;
                }
            })
        }

        if (!this.ref.current.contains(event.target) && clickedOutside) {
            onClickOutside(event)
        }
    }
```
[Source](https://github.com/langleyfoxall/react-click-outside/blob/master/src/ClickOutside.jsx#L14-L34).

Thoughts?

**Comment by NilesB** [comment]
It looks like you use your own ref, if you want to do this you can use the `domRef` prop. This will use that ref instead of attempting to override it. Also, when creating refs you should use the [createRef](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) method.

If `current` is not present the element is not in the dom. This means that it is probably trying to use the wrong ref because of one of the above issues.

**Comment by dextermb** [comment]
> It looks like you use your own ref, if you want to do this you can use the `domRef` prop. This will use that ref instead of attempting to override it. Also, when creating refs you should use the [createRef](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) method.
> 
> If `current` is not present the element is not in the dom. This means that it is probably trying to use the wrong ref because of one of the above issues.

Hm, not sure. The ref trigger ref used in `react-dropdown` does seem to exist in the DOM, at least when the callback is triggered

**Comment by dextermb** [comment]
> Also, when creating refs you should use the [createRef](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) method.

Also, this should only be used when you're doing something like:
```jsx
<div ref={ref => this.div = ref} />
```

But I am doing something similar to:
```jsx
<div ref={'trigger'} />
```

Which appends the ref to `this.refs` rather than directly on the element.

**Comment by dextermb** [comment]
Ah, seems like string refs were deprecated. I've created an [issue on my package to resolve it](https://github.com/ninetynine/react-dropdown/issues/1).
